import requests, json, sys
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
S=requests.Session(); S.headers.update({"User-Agent":"Mozilla/5.0 research/1.0"})
f=S.get("https://api.llama.fi/overview/fees?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyFees",timeout=120).json()
print("FEES keys:", list(f.keys()))
print("total24h:", f.get("total24h"), "total7d:", f.get("total7d"), "total30d:", f.get("total30d"), "total1y:", f.get("total1y"))
print("change_1d",f.get("change_1d"),"change_7d",f.get("change_7d"),"change_1m",f.get("change_1m"))
prs=f.get("protocols",[])
print("n protocols:",len(prs)); print("SAMPLE:",json.dumps(prs[0],indent=1)[:900])
d=S.get("https://api.llama.fi/overview/dexs?excludeTotalDataChart=true&excludeTotalDataChartBreakdown=true&dataType=dailyVolume",timeout=120).json()
print("\nDEX keys:", list(d.keys()))
print("total24h:", d.get("total24h"), "total30d:", d.get("total30d"))
print("change_7d",d.get("change_7d"),"change_1m",d.get("change_1m"))
print("SAMPLE dex:",json.dumps(d.get("protocols",[])[0],indent=1)[:700])
