# pragma pylint: disable=missing-docstring, invalid-name, pointless-string-statement
# flake8: noqa: F401
# isort: skip_file
# --- Do not remove these imports ---
import numpy as np
import pandas as pd
from datetime import datetime, timedelta, timezone
from pandas import DataFrame
from typing import Dict, Optional, Union, Tuple

from freqtrade.strategy import (
    IStrategy,
    Trade,
    Order,
    PairLocks,
    informative,  # @informative decorator
    # Hyperopt Parameters
    BooleanParameter,
    CategoricalParameter,
    DecimalParameter,
    IntParameter,
    RealParameter,
    # timeframe helpers
    timeframe_to_minutes,
    timeframe_to_next_date,
    timeframe_to_prev_date,
    # Strategy helper functions
    merge_informative_pair,
    stoploss_from_absolute,
    stoploss_from_open,
    AnnotationType,
)

# --------------------------------
# Add your lib to import here
import talib.abstract as ta
from technical import qtpylib


class ShortBreakout4h(IStrategy):
    """
    4h short-side volume breakout on Binance USD-M perps.

    Scaffold generated by `freqtrade new-strategy`; run with
    `freqtrade backtesting`. The logic is the FROZEN rule from
    docs-myself/PREREG_WIDE_PANEL_2026-09-27.md, unchanged:

        relative volume >= 2.0 over a 20-bar SMA
        20-bar Donchian breakout, SHORT side only (close < prev 20-bar low)
        low-vol regime: trailing 42-bar vol < its median over 365 bars
        stop  = 1.5 x ATR(14)
        target= 2R
        time stop = 42 bars (~7 days)

    TWO STATED DEVIATIONS from the shark_hunter engine, both forced:
      * the stop is a FIXED -0.036 (the panel's median 1.5x ATR%, measured on
        these 24 symbols as min 1.47% / median 3.61% / max 5.04%) rather than
        per-bar adaptive ATR. `custom_stoploss` was tried twice and both times
        produced a confident wrong answer: dividing by current_rate created a
        ratchet that closed losers in ~3 bars, and the entry-anchored version
        returned None so the -50% default applied. A fixed stop is the honest
        approximation.
      * funding is not modelled by freqtrade's backtester, so these numbers sit
        ABOVE the shark net by the funding term.
    """
    # Strategy interface version - allow new iterations of the strategy interface.
    INTERFACE_VERSION = 3

    timeframe = "4h"
    timeframe_min = 240

    can_short: bool = True

    # all exits are rule-based (target + time stop), so ROI is disabled
    minimal_roi = {"0": 100}

    # panel median 1.5 x ATR%
    stoploss = -0.036

    trailing_stop = False

    process_only_new_candles = False

    use_exit_signal = True
    exit_profit_only = False
    ignore_roi_if_entry_signal = False

    # low_vol needs vol42 (42) + a 365-bar median with 120 min_periods, and the
    # breakout/rvol need 20, so 420 is the true requirement (400 is not enough).
    startup_candle_count: int = 420

    rvol_period = 20
    rvol_threshold = 2.0
    breakout_period = 20
    atr_stop = 1.5
    target_r = 2.0
    time_stop_bars = 42
    vol_lookback = 42
    vol_med_window = 365

    # Strategy parameters
    buy_rsi = IntParameter(10, 40, default=30, space="buy")
    sell_rsi = IntParameter(60, 90, default=70, space="sell")# Optional order type mapping.
    order_types = {
        "entry": "limit",
        "exit": "limit",
        "stoploss": "market",
        "stoploss_on_exchange": False
    }

    # Optional order time in force.
    order_time_in_force = {
        "entry": "GTC",
        "exit": "GTC"
    }
    @property
    def plot_config(self):
        return {
            # Main plot indicators (Moving averages, ...)
            "main_plot": {
                "tema": {},
                "sar": {"color": "white"},
            },
            "subplots": {
                # Subplots - each dict defines one additional plot
                "MACD": {
                    "macd": {"color": "blue"},
                    "macdsignal": {"color": "orange"},
                },
                "RSI": {
                    "rsi": {"color": "red"},
                }
            }
        }

    def informative_pairs(self):
        """
        Define additional, informative pair/interval combinations to be cached from the exchange.
        These pair/interval combinations are non-tradeable, unless they are part
        of the whitelist as well.
        For more information, please consult the documentation
        :return: List of tuples in the format (pair, interval)
            Sample: return [("ETH/USDT", "5m"),
                            ("BTC/USDT", "15m"),
                            ]
        """
        return []


    # ------------------------------------------------------------------
    # Frozen rule (docs-myself/PREREG_WIDE_PANEL_2026-09-27.md)
    # ------------------------------------------------------------------
    def populate_indicators(self, dataframe: DataFrame, metadata: dict) -> DataFrame:
        """ATR(14), relative volume(20), 20-bar Donchian, and the frozen
        low-volatility regime filter.

        The breakout levels EXCLUDE the current bar (shift(1)), and the
        volatility median is shifted(1), so nothing here reads the bar it is
        deciding. The relative-volume average INCLUDES the current bar, which
        is causal because that bar's volume is complete at its close; this
        matches the shark engine's convention exactly.
        """
        df = dataframe.copy()

        prev_close = df["close"].shift(1)
        tr = pd.concat([
            df["high"] - df["low"],
            (df["high"] - prev_close).abs(),
            (df["low"] - prev_close).abs(),
        ], axis=1).max(axis=1)
        df["atr"] = tr.ewm(alpha=1.0 / 14.0, adjust=False,
                           min_periods=14).mean()

        vol = df["volume"].clip(lower=0.0)
        df["volume_sma"] = vol.rolling(self.rvol_period,
                                       min_periods=self.rvol_period).mean()
        df["rvol"] = vol / df["volume_sma"].replace(0.0, np.nan)

        df["prev_high"] = df["high"].rolling(self.breakout_period,
                                             min_periods=self.breakout_period
                                             ).max().shift(1)
        df["prev_low"] = df["low"].rolling(self.breakout_period,
                                           min_periods=self.breakout_period
                                           ).min().shift(1)

        # low-vol regime filter: trailing 42-bar vol below its own 365-bar median
        lr = np.log(df["close"]).diff()
        df["vol42"] = lr.rolling(self.vol_lookback,
                                 min_periods=self.vol_lookback).std()
        df["vol42_med"] = df["vol42"].rolling(
            self.vol_med_window, min_periods=120).median().shift(1)
        df["low_vol"] = (df["vol42"] < df["vol42_med"]).fillna(False)

        df["shark_short"] = ((df["rvol"] >= self.rvol_threshold)
                             & (df["close"] < df["prev_low"])
                             & df["low_vol"])
        return df

    def populate_entry_trend(self, dataframe: DataFrame, metadata: dict
                             ) -> DataFrame:
        """SHORT only. The long leg is net-negative in every cell and every
        cost regime of the wide-panel run.

        Conditions are evaluated on the signal candle's close; freqtrade fills
        at the next candle's open, matching the shark engine's convention.
        """
        dataframe.loc[dataframe["shark_short"],
                       ["enter_long", "enter_short"]] = (0, 1)
        dataframe.loc[~dataframe["shark_short"],
                       ["enter_long", "enter_short"]] = (0, 0)
        dataframe["enter_tag"] = np.where(dataframe["shark_short"],
                                          "shark_short", "")
        return dataframe

    def populate_exit_trend(self, dataframe: DataFrame, metadata: dict
                            ) -> DataFrame:
        """No signal exit: the 2R target and the time stop are rule-based."""
        dataframe["exit_long"] = 0
        dataframe["exit_short"] = 0
        dataframe["exit_tag"] = ""
        return dataframe

    def entry_atr(self, pair: str, trade):
        """ATR frozen at the ENTRY bar, not the current bar.

        WHY THIS IS FIXED 2026-09-27. The 2R target used to be measured with the
        LATEST ATR. ATR moves: a trade opened when ATR was 2% and closed when it
        was 4% had its target silently stretched by 2x, and one opened at 4% and
        closed at 2% had its target pulled in. That changes the payoff geometry,
        the holding time and the R distribution on every trade, so the backtest
        was not measuring the frozen rule (1.5 x ATR at entry, 2R from there).
        This is BASELINE INTEGRITY: this backtest is the yardstick every later
        strategy is compared against, and a yardstick with a moving target
        silently flatters or punishes every comparison made against it.
        """
        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        if df is None or len(df) < 2:
            return None
        try:
            entry_ts = pd.Timestamp(trade.open_date_utc).floor(self.timeframe)
        except (AttributeError, TypeError, ValueError):
            return None
        at_entry = df.loc[df["date"] == entry_ts, "atr"]
        if len(at_entry):
            v = float(at_entry.iloc[-1])
        else:
            # the entry bar is not in the analysed frame (start of the backtest);
            # fall back to the oldest available bar rather than the newest
            v = float(df["atr"].iloc[0])
        return v if np.isfinite(v) and v > 0 else None

    def custom_exit(self, pair: str, trade, current_time, current_rate: float,
                    current_profit: float, **kwargs) -> str | None:
        """2R from the ENTRY-bar ATR, else a 42-bar (~7 day) time stop."""
        df, _ = self.dp.get_analyzed_dataframe(pair, self.timeframe)
        if len(df) < 2:
            return None
        atr = self.entry_atr(pair, trade)
        if atr is None:
            atr = df["atr"].iloc[-1]
        if np.isfinite(atr) and atr > 0:
            target = trade.open_rate - self.target_r * self.atr_stop * atr
            if current_rate <= target:
                return "target_2r"
        # SECONDS PER BAR = timeframe_min * 60 (4h -> 14400). Dividing by 240
        # (seconds per HOUR) reads one 4h bar as 60 bars and force-exits ~85%
        # of trades on their entry bar.
        held = ((current_time - trade.open_date_utc).total_seconds()
                / (self.timeframe_min * 60))
        if held >= self.time_stop_bars:
            return "time_stop"
        return None
