"""Rebuild the state-file index MECHANICALLY from the per-round documents.

WHY THIS FILE EXISTS
--------------------
On 2026-09-30 an agent truncated `docs-myself/RESEARCH_STATE.md` to zero bytes
while doing line-index surgery on it in PowerShell, and it was untracked, so
~3,400 lines of accumulated project history were lost. The state file is an
INDEX over `docs-myself/*.md`; those 115 documents (1.1 MB) were untouched and
are the primary record.

Reconstructing an index by remembering what was in it is exactly the wrong
move: it is unverifiable and it invents. So the index is regenerated by reading
the documents themselves - every row below can be checked by opening the file
it names, and re-running this script regenerates it deterministically.

IT IS AN INDEX, NOT A SUBSTITUTE. A document row says what a file is; it does
not replace reading the file. Nothing here is a verdict of this project - it is
a table of contents with whatever verdict each document states about itself.

Run:
    .venv\\Scripts\\python.exe tools\\state_index.py            # print
    .venv\\Scripts\\python.exe tools\\state_index.py --write    # -> tmp
"""

from __future__ import annotations

import re
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs-myself"

# The three files that are not round documents.
INFRA = {"RESEARCH_STATE.md", "RESEARCH_GOAL.md", "START_HERE.md"}

# A verdict keyword seen in a document's own summary line. The FIRST such line
# in the first ~40 lines is taken as that document's self-stated verdict.
VERDICT_RE = re.compile(
    r"(VERDICT|判定|结论|判定为|PASS|FAIL|CLOSED|REJECTED|INCONCLUSIVE|BLOCKED|"
    r"NOT SUPPORTED|REFUTED|ACCEPTED|SURVIVOR|关闭|不成立|通过)",
    re.IGNORECASE)

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")


def classify(name: str) -> str:
    n = name.upper()
    if n.startswith("PREREG"):
        return "prereg"
    if n.startswith("RESULT") or "_RESULT" in n or n.startswith("E") and "_RESULT" in n:
        return "result"
    if n.startswith("FINDINGS-") or n.startswith("findings-"):
        return "finding"
    if "CORRECTION" in n:
        return "correction"
    if n.startswith("LITERATURE") or "LIT_REVIEW" in n or n.startswith("XSECT"):
        return "literature"
    if n.startswith("RUNBOOK"):
        return "runbook"
    if "GATE0" in n or "GATE-0" in n or "POWER" in n:
        return "gate0"
    if n.startswith("HOW_TO_RUN"):
        return "howto"
    if n.startswith("VERDICT") or "VERDICT" in n:
        return "verdict"
    if n.startswith("LESSON") or n.startswith("TERMINAL") or n.startswith("R7_"):
        return "lesson"
    return "other"


def _is_junk(s: str) -> bool:
    """Lines that carry no information: bare section numbers, or a two-word
    Chinese heading like '0. 结论'."""
    t = s.strip()
    if len(t) < 12:
        return True
    if re.match(r"^\d+(\.\d+)*[.、]?\s*$", t):
        return True
    if re.match(r"^\d+(\.\d+)*[.、]\s*\S{0,6}$", t):
        return True
    if t in {"结论", "一句话", "结果", "判定", "说明", "摘要", "背景", "范围"}:
        return True
    if t.startswith("|") and t.endswith("|"):
        return True
    return False


def summarise(path: Path, maxlen: int = 260) -> tuple[str, str]:
    """(title, self-stated verdict line) from the document's own text."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ("<unreadable>", "")
    lines = text.splitlines()
    title = ""
    verdict = ""
    for i, ln in enumerate(lines[:60]):
        s = ln.strip().lstrip("#").strip()
        if not s:
            continue
        if not title and i == 0 and len(s) > 3 and not s.startswith(">"):
            title = s
            continue
        if not verdict and VERDICT_RE.search(ln) and not _is_junk(s):
            verdict = re.sub(r"[*`]+", "", s)
            break
    if not verdict:
        # fall back to the first substantive line
        for ln in lines[:40]:
            s = ln.strip().lstrip("#").strip()
            if not _is_junk(s):
                verdict = re.sub(r"[*`]+", "", s)
                break
    verdict = re.sub(r"\s+", " ", verdict)[:maxlen]
    title = re.sub(r"\s+", " ", title)[:120] or path.stem
    return title, verdict


ANCHOR = "<!--GENERATED-INDEX-->"


def main(argv: list[str]) -> int:
    files = sorted(p for p in DOCS.glob("*.md")
                   if p.name not in INFRA and not p.name.startswith("_"))
    rows = []
    for p in files:
        m = DATE_RE.search(p.name)
        d = m.group(1) if m else "(undated)"
        title, verdict = summarise(p)
        rows.append((d, p.name, classify(p.name), title, verdict, p.stat().st_size))

    by_date: dict[str, int] = {}
    for d, *_ in rows:
        by_date[d] = by_date.get(d, 0) + 1

    out = []
    out.append("## 1a. DOCUMENT INDEX — every round's record, mechanically regenerated")
    out.append("")
    out.append(f"**{len(rows)} documents, "
               f"{sum(r[5] for r in rows)/1024:.0f} KB, in `docs-myself/`.** "
               f"This table is produced by `tools/state_index.py`, which reads the "
               f"documents' own summary lines. It is a **table of contents, not a "
               f"set of verdicts** — open the file to get the finding. Regenerate "
               f"with `.venv\\Scripts\\python.exe tools\\state_index.py`.")
    out.append("")
    out.append("| date | document | kind | what it says (its own summary line) |")
    out.append("|---|---|---|---|")
    for d, name, kind, title, verdict, size in sorted(rows, reverse=True):
        v = verdict.replace("|", "\\|")
        out.append(f"| {d} | [`{name}`]({name}) | {kind} | {v} |")
    out.append("")
    out.append("**By date:** " + ", ".join(
        f"{k} {v}" for k, v in sorted(by_date.items(), reverse=True)))
    out.append("")

    text = "\n".join(out)
    if "--build" in argv:
        # Rebuild the whole state file as: hand-written header + generated index.
        # RESEARCH_STATE.md is now GENERATED, which is the point: the 2026-09-30
        # loss happened because a 3,400-line hand-edited index was the only copy
        # of its own contents. A generated file can be regenerated; a
        # hand-edited one can only be lost.
        header = DOCS / "_STATE_HEADER.md"
        if not header.exists():
            print(f"missing {header}; refusing to write a state file with no body")
            return 1
        state = DOCS / "RESEARCH_STATE.md"
        body = header.read_text(encoding="utf-8")
        if ANCHOR in body:
            # Place the index where the header asks for it, so the section
            # numbering reads in order rather than appending a "1a" at the end.
            body = body.replace(ANCHOR, text)
        else:
            if not body.rstrip().endswith("---"):
                body = body.rstrip() + "\n\n---\n"
            body = body.rstrip() + "\n\n" + text
        state.write_text(body, encoding="utf-8")
        n = len(state.read_text(encoding="utf-8").splitlines())
        print(f"rebuilt {state} : {n} lines, {len(rows)} indexed documents")
        print(f"  (hand-written part: {header.name}; index: tools/state_index.py)")
        if n < 200:
            print("  WARNING: that is far shorter than expected. Check the header.")
            return 1
        return 0
    if "--write" in argv:
        dest = ROOT / "docs-myself" / "_GENERATED_INDEX.md"
        dest.write_text(text, encoding="utf-8")
        print(f"wrote {dest} ({len(text)} chars, {len(rows)} rows)")
    else:
        # The Windows console defaults to GBK here, and these documents are full
        # of U+2212 MINUS SIGN and similar. Reconfigure stdout rather than
        # stripping the characters - the text is the deliverable.
        try:
            sys.stdout.reconfigure(encoding="utf-8", errors="replace")
        except AttributeError:
            pass
        print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
